{% set name = "mpltern" %}
{% set version = "1.0.4" %}
{% set sha256 = "204d54227406eea54b602abac1617d0e3c2c2484fbd6718f455c238bca7cc60d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.1.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - mpltern

about:
  home: https://yuzie007.github.io/mpltern
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Ternary plots as projections of Matplotlib

  description: |
    Mpltern is a Python plotting library based on Matplotlib specifically designed for ternary plots. Mpltern is implemented as a new projection for Matplotlib, with introducing e.g. new Transform classes for ternary plots.

  doc_url: https://yuzie007.github.io/mpltern
  dev_url: https://github.com/yuzie007/mpltern

extra:
  recipe-maintainers:
    - yuzie007
