{% set name = "mpltern" %}
{% set version = "0.3.5" %}
{% set sha256 = "42c9d0b0181145a3f722026e30b1d47e5b4de89c954607d3900d1a2fbd26690e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - matplotlib-base >=3.1.1

test:
  imports:
    - mpltern

about:
  home: https://yuzie007.github.io/mpltern
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Ternary plots as projections of Matplotlib

  description: |
    Mpltern is a Python plotting library based on Matplotlib specifically designed for ternary plots. Mpltern is implemented as a new projection for Matplotlib, with introducing e.g. new Transform classes for ternary plots.

  doc_url: https://yuzie007.github.io/mpltern
  dev_url: https://github.com/yuzie007/mpltern

extra:
  recipe-maintainers:
    - yuzie007
