{% set name = "mpltern" %}
{% set version = "1.0.3" %}
{% set sha256 = "38388060b60c6bd71c401a031430bd4a42c8ec57df85887e10219d3f85ecd0cf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - matplotlib-base >=3.1.1

test:
  imports:
    - mpltern

about:
  home: https://yuzie007.github.io/mpltern
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Ternary plots as projections of Matplotlib

  description: |
    Mpltern is a Python plotting library based on Matplotlib specifically designed for ternary plots. Mpltern is implemented as a new projection for Matplotlib, with introducing e.g. new Transform classes for ternary plots.

  doc_url: https://yuzie007.github.io/mpltern
  dev_url: https://github.com/yuzie007/mpltern

extra:
  recipe-maintainers:
    - yuzie007
